src/App.js

new elements

---

src/App.js

new header

---

src/pages/homepage/HomePage.css

Padding on the bottom of homepage

---

package-lock.json
package.json
src/components/navigation/Navigation.js
src/helpers/mediaQueries.js

Some changes to the nanigation page, not done, need to change the code

changes in nav component, still in progress

---

src/App.js
src/components/imagecarousel/ImageCarouselItem.css
src/components/imagecarousel/ImageCarouselItem.js
src/components/imagecarousel/ImagePopup.css
src/components/shared/locationbar/LocationBar.js
src/components/shared/locationbar/locationBar.css

fixed scaling for the header in the slide component, the text popup is now scrollable and scalable, and the active link is fixed.

fixed active link and slide component

---

src/components/shared/locationbar/locationBar.css

@media fix

---

src/pages/homepage/HomePage.css

fixed grid gap and padding youtube

small adjusments grid

---

src/components/cardtwo/CardTwo.css
src/components/circlebutton/CircleNavStyle.css
src/components/navigation/Navigation.js
src/pages/homepage/HomePage.css
src/pages/navigationpage/NavigationPage.css
src/pages/navigationpage/NavigationPage.js

media queries good enough on the navigation component

media queries on navigation component

---

src/components/youtubevideo/YouTubePlayer.css

superquick fix after merge conflict

last youtube fix

---

src/components/worksSubCategory/SubCategoryItem.js
src/pages/subcategorypage/SubCategoryPage.css

small change

---

src/components/worksSubCategory/SubCategoryItem.css

just a quick margin fix on the h3 for the subcategories.

margin fix

---

src/App.js
src/components/soundbox/SoundBox.css
src/components/soundbox/SoundBox.js
src/components/sounditem/SoundItem.js
src/pages/index.js
src/pages/soundpage/SoundPage.css
src/pages/soundpage/SoundPage.js

new audio component and audio item and also done for now setup of audio page

new audio com and audio page

---

src/components/worksSubCategory/SubCategoryItem.css
src/components/worksSubCategory/SubCategoryItem.js

Not done yet, but had to push so that i can work in app.js

Trying to fix active link

---

src/components/sounditem/SoundItem.css
src/components/sounditem/SoundItem.js

working rewind and forward button on the soundItem

forward rewind fix audio

---

package-lock.json
package.json
src/App.js
src/components/videobox/VideoBox.css
src/components/videobox/VideoBox.js
src/components/videoitem/VideoItem.css
src/components/videoitem/VideoItem.js
src/pages/index.js
src/pages/videopage/VideoPage.css
src/pages/videopage/VideoPage.js

videocomponent added and videoPage good enough

video com and vide page close to finnished

---

src/components/navigation/Navigation.js

linked the restoring pages to the nav component

linking nav page

---

src/pages/imagegallerypage/ImageGalleryPage.css
src/pages/imagegallerypage/ImageGalleryPage.js
src/pages/soundpage/SoundPage.css
src/pages/soundpage/SoundPage.js
src/pages/subcategorypage/SubCategoryPage.css
src/pages/subcategorypage/SubCategoryPage.js
src/pages/videopage/VideoPage.css
src/pages/videopage/VideoPage.js
src/pages/workspage/WorkPage.css
src/pages/workspage/WorkPage.js

Added a back feature for each page in navigation.

backArrow for all the pages needed

---

src/components/workitem/WorkItem.css

media queries books

---

src/components/workitem/WorkItem.css

media queries books small fixes

---

src/components/ImageWithText/Text.js
src/pages/homepage/HomePage.js
src/pages/videopage/VideoPage.js

fixed the titles an description video page and two buttons on home page

new titles and description video and buttons homepage

---

package-lock.json
package.json

removed react-planet from dependencies and node_modules

removed react-planet

---

package-lock.json
package.json

removed slick-carousel from json and node modules

removed slick-carousel

---

src/components/workitem/WorkItem.css

css fix work item
